version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-trendhive
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: trendhive
      MYSQL_USER: trendhive_user
      MYSQL_PASSWORD: yourpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - trendhive-network

  redis:
    image: redis:latest
    container_name: redis-trendhive
    restart: always
    ports:
      - "6379:6379"
    networks:
      - trendhive-network

volumes:
  mysql_data:

networks:
  trendhive-network:
    driver: bridge
